apiVersion: apps/v1 
kind: Deployment
metadata:
  name: watch-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: watch
        image: tonpaes/aguasur
        ports:
        - containerPort: 80