apiVersion: v1
kind: Service
metadata:
  name: watch-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: watch
      port: 80
      targetPort: 80
      