apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - name: mongo-api
      port: 80
      targetPort: 8000
      
    - name: mongo-mongo
      port: 27017
      targetPort: 27017